# Generated by Django 3.1.5 on 2021-05-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-id']},
        ),
    ]
